#!/usr/bin/perl -w
#treat mapping result,get reads' chrom and 5' site,seperated by TAB.
open SAM_FH,'<','/leofs/wangqf_group/zhanglx/yang/bwa/CON_MSCs_RNAPol2.unique.sort.rmdup.sam' or die "Cannot open samfile:$!";
open MAP_FH,'>','/leofs/wangqf_group/zhanglx/yang/bwa/CON.aln'or die "$!";
while(my $lines = <SAM_FH>){
	chomp($lines);
	my @lines = split"\t",$lines;
	if ($lines[2] == 0){printf MAP_FH "%s\t%s\t%s\n",$lines[3],$lines[4],F;}
	elsif ($lines[2] == 16){printf MAP_FH "%s\t%s\t%s\n",$lines[3],$lines[4],R;}
}
close SAM_FH;
close MAP_FH;
